title: Pravesha 2018
description: > # this means to ignore newlines until "baseurl:"
  A National level Computer science symposium
baseurl: "" # the subpath of your site, e.g. /blog
url: "Your-Link.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Pravesha 2018
  link: "https://www.instagram.com/pravesha18/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/pravesha18/

# Build settings
markdown: kramdown
permalink: pretty
